export const USER_SIGNIN_REQUEST = 'USER_SIGNIN_REQUEST'
export const USER_SIGNIN_SUCCESS = 'USER_SIGNIN_SUCCESS'
export const USER_SIGNIN_FAIL = 'USER_SIGNIN_FAIL'

export const USER_SIGNOUT = "USER_SIGNOUT"

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST'
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS'
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL'

export const USER_MY_EVENTS_REQUEST = 'USER_MY_EVENTS_REQUEST'
export const USER_MY_EVENTS_SUCCESS = 'USER_MY_EVENTS_SUCCESS'
export const USER_MY_EVENTS_FAIL = 'USER_MY_EVENTS_FAIL'

export const USER_COMMUNITY_EVENTS_REQUEST = 'USER_COMMUNITY_EVENTS_REQUEST'
export const USER_COMMUNITY_EVENTS_SUCCESS = 'USER_COMMUNITY_EVENTS_SUCCESS'
export const USER_COMMUNITY_EVENTS_FAIL = 'USER_COMMUNITY_EVENTS_FAIL'