export const USER_SIGNIN_REQUEST = 'USER_SIGNIN_REQUEST'
export const USER_SIGNIN_SUCCESS = 'USER_SIGNIN_SUCCESS'
export const USER_SIGNIN_FAIL = 'USER_SIGNIN_FAIL'

export const USER_SIGNOUT = "USER_SIGNOUT"

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST'
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS'
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL'

export const USER_MY_EVENTS_REQUEST = 'USER_MY_EVENTS_REQUEST'
export const USER_MY_EVENTS_SUCCESS = 'USER_MY_EVENTS_SUCCESS'
export const USER_MY_EVENTS_FAIL = 'USER_MY_EVENTS_FAIL'

export const USER_COMMUNITY_EVENTS_REQUEST = 'USER_COMMUNITY_EVENTS_REQUEST'
export const USER_COMMUNITY_EVENTS_SUCCESS = 'USER_COMMUNITY_EVENTS_SUCCESS'
export const USER_COMMUNITY_EVENTS_FAIL = 'USER_COMMUNITY_EVENTS_FAIL'

export const USER_SCHEDULE_EVENTS_REQUEST = 'USER_SCHEDULE_EVENTS_REQUEST'
export const USER_SCHEDULE_EVENTS_SUCCESS = 'USER_SCHEDULE_EVENTS_SUCCESS'
export const USER_SCHEDULE_EVENTS_FAIL = 'USER_SCHEDULE_EVENTS_FAIL'

export const USER_PROFILE_REQUEST = 'USER_PROFILE_REQUEST'
export const USER_PROFILE_SUCCESS = 'USER_PROFILE_SUCCESS'
export const USER_PROFILE_FAIL = 'USER_PROFILE_FAIL'

export const USER_CREATE_EVENT_REQUEST = 'USER_CREATE_EVENT_REQUEST'
export const USER_CREATE_EVENT_SUCCESS = 'USER_CREATE_EVENT_SUCCESS'
export const USER_CREATE_EVENT_FAIL = 'USER_CREATE_EVENT_FAIL'
export const USER_CREATE_EVENT_RESET = 'USER_CREATE_EVENT_RESET'

export const USER_UPDATE_EVENT_REQUEST = 'USER_UPDATE_EVENT_REQUEST'
export const USER_UPDATE_EVENT_SUCCESS = 'USER_UPDATE_EVENT_SUCCESS'
export const USER_UPDATE_EVENT_FAIL = 'USER_UPDATE_EVENT_FAIL'
export const USER_UPDATE_EVENT_RESET = 'USER_UPDATE_EVENT_RESET'

export const USER_REMOVE_EVENT_REQUEST = 'USER_REMOVE_EVENT_REQUEST'
export const USER_REMOVE_EVENT_SUCCESS = 'USER_REMOVE_EVENT_SUCCESS'
export const USER_REMOVE_EVENT_FAIL = 'USER_REMOVE_EVENT_FAIL'
export const USER_REMOVE_EVENT_RESET = 'USER_REMOVE_EVENT_RESET'

export const USER_REGISTER_EVENT_REQUEST = 'USER_REGISTER_EVENT_REQUEST'
export const USER_REGISTER_EVENT_SUCCESS = 'USER_REGISTER_EVENT_SUCCESS'
export const USER_REGISTER_EVENT_FAIL = 'USER_REGISTER_EVENT_FAIL'
export const USER_REGISTER_EVENT_RESET = 'USER_REGISTER_EVENT_RESET'

export const USER_UNREGISTER_EVENT_REQUEST = 'USER_UNREGISTER_EVENT_REQUEST'
export const USER_UNREGISTER_EVENT_SUCCESS = 'USER_UNREGISTER_EVENT_SUCCESS'
export const USER_UNREGISTER_EVENT_FAIL = 'USER_UNREGISTER_EVENT_FAIL'
export const USER_UNREGISTER_EVENT_RESET = 'USER_UNREGISTER_EVENT_RESET'



